/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authForgetRouteImport } from './routes/(auth)/forget'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as blogBlogSlugRouteImport } from './routes/(blog)/blog/$slug'
import { Route as blogIndexRouteImport } from './routes/(blog)/index'
import { Route as blogRouteRouteImport } from './routes/(blog)/route'
import { Route as AdminBlogCreateRouteImport } from './routes/admin/blog/create'
import { Route as AdminRouteRouteImport } from './routes/admin/route'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const blogRouteRoute = blogRouteRouteImport.update({
  id: '/(blog)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const blogIndexRoute = blogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => blogRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgetRoute = authForgetRouteImport.update({
  id: '/forget',
  path: '/forget',
  getParentRoute: () => authRouteRoute,
} as any)
const AdminBlogCreateRoute = AdminBlogCreateRouteImport.update({
  id: '/blog/create',
  path: '/blog/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const blogBlogSlugRoute = blogBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => blogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/forget': typeof authForgetRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof blogIndexRoute
  '/blog/$slug': typeof blogBlogSlugRoute
  '/admin/blog/create': typeof AdminBlogCreateRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRouteWithChildren
  '/forget': typeof authForgetRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof blogIndexRoute
  '/blog/$slug': typeof blogBlogSlugRoute
  '/admin/blog/create': typeof AdminBlogCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(blog)': typeof blogRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(auth)/forget': typeof authForgetRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(blog)/': typeof blogIndexRoute
  '/(blog)/blog/$slug': typeof blogBlogSlugRoute
  '/admin/blog/create': typeof AdminBlogCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/forget'
    | '/login'
    | '/register'
    | '/'
    | '/blog/$slug'
    | '/admin/blog/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/forget'
    | '/login'
    | '/register'
    | '/'
    | '/blog/$slug'
    | '/admin/blog/create'
  id:
    | '__root__'
    | '/(auth)'
    | '/(blog)'
    | '/admin'
    | '/(auth)/forget'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(blog)/'
    | '/(blog)/blog/$slug'
    | '/admin/blog/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  blogRouteRoute: typeof blogRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)': {
      id: '/(blog)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof blogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/': {
      id: '/(blog)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof blogIndexRouteImport
      parentRoute: typeof blogRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forget': {
      id: '/(auth)/forget'
      path: '/forget'
      fullPath: '/forget'
      preLoaderRoute: typeof authForgetRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/admin/blog/create': {
      id: '/admin/blog/create'
      path: '/blog/create'
      fullPath: '/admin/blog/create'
      preLoaderRoute: typeof AdminBlogCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(blog)/blog/$slug': {
      id: '/(blog)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof blogBlogSlugRouteImport
      parentRoute: typeof blogRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgetRoute: typeof authForgetRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgetRoute: authForgetRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren
)

interface blogRouteRouteChildren {
  blogIndexRoute: typeof blogIndexRoute
  blogBlogSlugRoute: typeof blogBlogSlugRoute
}

const blogRouteRouteChildren: blogRouteRouteChildren = {
  blogIndexRoute: blogIndexRoute,
  blogBlogSlugRoute: blogBlogSlugRoute,
}

const blogRouteRouteWithChildren = blogRouteRoute._addFileChildren(
  blogRouteRouteChildren
)

interface AdminRouteRouteChildren {
  AdminBlogCreateRoute: typeof AdminBlogCreateRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBlogCreateRoute: AdminBlogCreateRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  blogRouteRoute: blogRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
